version: "2"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - JELLYFIN_PublishedServerUrl=kino-szymona.duckdns.org #optional
    volumes:
      - /home/szymon/docker/jellyfin_config:/config
      - /home/szymon/clouds/firstPcloud/media/shows:/data/tvshows
      - /home/szymon/clouds/firstPcloud/media/movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped
